[package]
name = "vpn"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
confy = "0.6.1"
serde = { version = "1.0.219", features = ["derive"] }
